#!/bin/bash

if [ -f "$HOME/.ssh/id_rsa" -o -f "$HOME/.ssh/id_rsa.pub" ]; then
    echo "WARNING!!! $HOME/.ssh/id_rsa & $HOME/.ssh/id_rsa.pub exists"
    exit 1
fi

mkdir -p $HOME/.ssh
ssh-keygen -t rsa -N '' -C "$(whoami)@localhost" -f $HOME/.ssh/id_rsa
cd $HOME
cat .ssh/id_rsa.pub >> .ssh/authorized_keys
chmod 700 .ssh && chmod 600 .ssh/authorized_keys
chmod 600 .ssh/id_rsa && chmod 644 .ssh/id_rsa.pub

echo "rsawrapper.user_scripts creating $HOME/.ssh/id_rsa"
echo "rsawrapper.user_scripts creating $HOME/.ssh/id_rsa.pub"
echo "rsawrapper.user_scripts creating $HOME/.ssh/authorized_keys"

